const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
function service(){
 const records=new Map();let sequence=0;
 const bucket={file(name,opts={}){return {async getMetadata(){const v=records.get(name);if(!v)throw Object.assign(Error(),{code:404});return [{generation:v.generation}];},async download(){const v=records.get(name);if(!v)throw Object.assign(Error(),{code:404});return [Buffer.from(JSON.stringify(v.data))];},async save(text,o){const v=records.get(name);if(String(o.preconditionOpts.ifGenerationMatch)!==String(v?.generation||0))throw Object.assign(Error(),{code:412});records.set(name,{data:JSON.parse(text),generation:String(++sequence)});}};}};
 const context=vm.createContext({module:{exports:{}},Buffer,Date,require(name){if(name==='firebase-admin/storage')return {getStorage:()=>({bucket:()=>bucket})};if(name==='firebase-admin/auth')return {getAuth:()=>({createCustomToken:async(uid,claims)=>JSON.stringify(claims)})};return require(name);}});
 vm.runInContext(fs.readFileSync(__dirname+'/upload-admission.js','utf8'),context);return {...context.module.exports,records};
}
const b=i=>({clientKey:'a'.repeat(64),session:'2026-10-04_03-00-00_'+String(i).padStart(12,'0'),files:[{name:'01_x.mp4',size:100,type:'video/mp4'}]});
test('concurrent admission updates cannot lose reservations',async()=>{const s=service();const results=await Promise.all([s.authorize(b(1)),s.authorize(b(2)),s.authorize(b(1))]);assert.ok(results.every(r=>r.status===200));assert.equal(s.records.get('_tipsecurity/admission.json').data.events.length,2);const grant=JSON.parse(results[0].body.token);assert.deepEqual(grant.tipFiles,{'01_x.mp4':100});});
test('IP abuse stops source delivery, including earlier queued sessions after cooldown',async()=>{const s=service();await s.authorize(b(1));assert.equal(await s.allowedSession(b(1).session),true);for(let i=2;i<=4;i++)await s.authorize({...b(i),files:[{...b(i).files[0],size:999999999}]});assert.equal(await s.allowedSession(b(1).session),false);s.records.get('_tipsecurity/admission.json').data.clients['a'.repeat(64)].blockedUntil=0;assert.equal(await s.allowedSession(b(1).session),false);assert.equal(await s.allowedSession(b(99).session),false);});
test('after cutover missing admission is denied but original older tips remain accessible',async()=>{const s=service();s.records.set('_tipsecurity/config.json',{generation:'1',data:{enforcedAfter:'2026-10-04T10:00:00Z'}});assert.equal(await s.permittedObject({name:'tips/'+b(1).session+'/_submission.json',timeCreated:'2026-10-04T11:00:00Z'}),false);assert.equal(await s.permittedObject({name:'tips/'+b(1).session+'/_submission.json',timeCreated:'2026-10-04T09:00:00Z'}),true);});
