window.MERCH_CATALOG = [
    {
        id: 'independent-news-supporter-bundle',
        name: 'Independent News Supporter Bundle',
        description: 'All four 2-inch holographic colorways plus one 4-inch Stay Classy sticker.',
        details: 'A limited-release set, layered by hand with premium weather-resistant vinyl and fade-resistant color.',
        price: 2999,
        shipping: 199,
        available: true,
        featured: true,
        hideOptions: true,
        bundleSummary: [
            { count: '4', label: '2-inch colorways' },
            { count: '1', label: '4-inch Stay Classy' },
        ],
        variants: [
            {
                id: 'complete-five-sticker-set',
                name: 'Complete five-sticker set',
                image: '/images/merchandise/chris-cerney-black-gold-holographic.webp',
                imageAlt: 'Independent News Supporter Bundle with all four 2-inch colorways and one 4-inch Stay Classy sticker',
                images: [
                    '/images/merchandise/chris-cerney-black-gold-holographic.webp',
                    '/images/merchandise/chris-cerney-gold-holographic.webp',
                    '/images/merchandise/chris-cerney-coastal-blue.webp',
                    '/images/merchandise/chris-cerney-silver-holographic.webp',
                    '/images/merchandise/stay-classy-4-inch.webp',
                ],
            },
        ],
    },
    {
        id: 'sticker-4-inch',
        name: '4-Inch Stay Classy Sticker',
        description: 'A 4-inch holographic die-cut Stay Classy Central Coast sticker.',
        details: 'Layered by hand with premium, heavy-duty, weather-resistant vinyl and color built into the material for a fade-resistant finish.',
        price: 1300,
        shipping: 299,
        sizeReference: '/images/merchandise/stay-classy-4-inch-size.webp',
        sizeReferenceAlt: 'Four-inch Stay Classy sticker shown with a measurement overlay',
        available: true,
        variants: [
            {
                id: 'stay-classy',
                name: 'Stay Classy Central Coast',
                image: '/images/merchandise/stay-classy-4-inch.webp',
                imageAlt: 'Holographic Stay Classy Central Coast sticker designed by Talpaworks',
            },
        ],
    },
    {
        id: 'sticker-2-inch',
        name: '2-Inch Chris Cerney Sticker',
        description: 'A 2-inch round portrait sticker available in four holographic colorways.',
        details: 'Layered by hand with premium, heavy-duty, weather-resistant vinyl and color built into the material for a fade-resistant finish.',
        price: 600,
        shipping: 99,
        sizeReference: '/images/merchandise/chris-cerney-2-inch-size.webp',
        sizeReferenceAlt: 'Two-inch Chris Cerney sticker shown with a measurement overlay',
        lifestyleImage: '/images/merchandise/chris-cerney-2-inch-in-hand.webp',
        lifestyleImageAlt: 'Two-inch holographic Chris Cerney sticker held in a hand for scale',
        available: true,
        variants: [
            {
                id: 'black-gold-holographic',
                name: 'Black and Gold Holographic',
                image: '/images/merchandise/chris-cerney-black-gold-holographic.webp',
                imageAlt: 'Black and gold holographic Chris Cerney portrait sticker',
            },
            {
                id: 'gold-holographic',
                name: 'Gold Holographic',
                image: '/images/merchandise/chris-cerney-gold-holographic.webp',
                imageAlt: 'Gold and iridescent Chris Cerney portrait sticker',
            },
            {
                id: 'coastal-blue',
                name: 'Coastal Blue',
                image: '/images/merchandise/chris-cerney-coastal-blue.webp',
                imageAlt: 'Teal and blue Chris Cerney portrait sticker',
            },
            {
                id: 'silver-holographic',
                name: 'Silver Holographic',
                image: '/images/merchandise/chris-cerney-silver-holographic.webp',
                imageAlt: 'Silver holographic and gold Chris Cerney portrait sticker',
            },
        ],
    },
];
